### ISSUE TITLE
No issue, just checking in on Mamba on Julia 0.5-

### ISSUE THREAD

**Issue by goedman** [brian-j-smith/Mamba.jl#102]
Hi Brian,

Worked today on updating Stan.jl to Julia 0.5 and in the process noted that on my OSX/Julia 0.5- system Mamba branch v0.10.0 happily completes Pkg.test("Mamba"). Stan.jl also works great with Mamba (v0.10.0) graphics and Gadfly 0.4.3 on Julia 0.5-.

I personally like Gadfly and really would like the Stan and Mamba outputs to remain easily comparable, but if you ever think about switching to a PlotsRecipe, let me know.

On my system, where I updated Graphs.jl awaiting the outstanding commit on JuliaLang/Graphs.jl, I get no longer any warnings.

Just wanted to let you know. Will close this item in a day or two.

Regards,
Rob

**Comment by brian-j-smith** [comment]
It sure is nice to see an issue opened saying that things are working :)  Glad to hear that about Mamba and especially about the warnings being fixed in Graphs.

You're the second person I've heard mention PlotsRecipe as a consideration for Mamba.  It looks interesting.  I like Gadfly too, but if someone (else) is interested in doing an implementation in a different package, all of the plotting code for Mamba is in a single file of ~200 lines.  I'll let you know if anything happens on that front.
