### ISSUE TITLE
Release new version dependent on Light Graphs?

### ISSUE THREAD

**Issue by chriselrod** [brian-j-smith/Mamba.jl#113]
The current release (version 0.10) is still dependent on Graphs instead of Light Graphs, and results in errors using Julia v 0.6.0 rc2 on my machine. Simply switching to the master solved the problem.

Is this a broader issue?
If so, in preparation for the arrival of 0.6.0, why not release a new tagged version? It has been 7 months since any updates on master.

**Comment by brian-j-smith** [comment]
The latest changes in the master branch are now available in release 0.10.1 of Mamba.

Do note, however, that the package is not currently compatible with julia 0.6 due to a broader issue concerning changes made to the language's AST syntax.  A similar issue occurred in going from julia 0.4 to 0.5.  As has been done in the past with Mamba, the package will be updated to work with the latest release of julia.  Most likely, the updates will be done shortly before or after the official release of julia 0.6.

**Comment by jpfairbanks** [comment]
Is there anything with respect to LightGraphs that is needed for updating Mamba?

**Comment by brian-j-smith** [comment]
LightGraphs is incorporated in the current release of Mamba and has been working great.  Mamba has also been successfully updated for full compatibility with julia 0.6.  From my perspective, I do not see that there are any changes needed to LightGraphs at this time for our application.

Unless I hear otherwise, I can go ahead and close this issue.

Thanks for checking in!
