### ISSUE TITLE
Nodes in Models - Mamba

### ISSUE THREAD

**Issue by lucasfreitas1988** [brian-j-smith/Mamba.jl#134]
Hello! I'm a Brazilian NewBie in Julia. I want to use Mamba.
I can not use the examples available in Git, a "Model is not defined" message appears.
My Julia version is 0.6.2 and i use the atom.
In nodes, appears the mensage "An unmonitored node of type "Mamba.ScalarStochastic" NaN"

I need help!

Thank you

**Comment by bdeonovic** [comment]
As per our discussion in e-mail:

Your error is a simple one: since you loaded both JuMP and Mamba, and since both export a function called `Model` you MUST qualify the use of Model with the module that you want to use it from. i.e. if you want to use Mamba's Model function you have to write:

model = Mamba.Model(....)

Otherwise julia won't know which `Model` you are trying to use! Note when I ran your code I got the following warning:

WARNING: both JuMP and Mamba export "Model"; uses of it in module Main must be qualified
ERROR: UndefVarError: Model not defined

which basically tells you the issue right there. Warnings are important, take notice! 

Good luck and let me know if you have any other issues.

**Comment by lucasfreitas1988** [comment]
Thank you very much!

I am a native of R and I still take my first steps in Julia. I am lucky to find a participatory community, I think this is fundamental for language to develop. We are on the right way.

Best regards!
