### ISSUE TITLE
LoadError: UndefVarError: Graphics not defined thrown by Color

### ISSUE THREAD

**Issue by scidom** [brian-j-smith/Mamba.jl#25]
@brian-j-smith there seems to be an issue wtih `Mamba` and `Color`, see https://github.com/JuliaLang/Color.jl/issues/84?

**Comment by brian-j-smith** [comment]
Hi @scidom,

If I understand the issue as described in the Color.jl thread, the LoadError you encountered was due to the Color package being pinned to an earlier version.  Older versions of Mamba did that, but the latest one (0.4.4) does not have any restrictions on the Color package version and should not cause the error.  Perhaps you had a pre-0.4.4 version of Mamba installed?

**Comment by scidom** [comment]
Hi @brian-j-smith, I had installed everything from scratch so it is not possible that I have an old version of Mamba - is METADATA up to speed with the latest Mamba commit?

**Comment by brian-j-smith** [comment]
I see the issue.  It occurs in julia 0.4, but not julia 0.3.  Mamba versions 0.4.4 and earlier are not compatible with julia 0.4.  Mamba 0.4.4 explicitly requires julia 0.3.x, whereas earlier Mamba versions only required julia 0.3 or later.  Apparently, julia 0.4 installs the latest Mamba package whose requirement is consistent with that version of the language, which is Mamba 0.4.3 - the one that pins the Color package.

I'm traveling over the next few days and will try to find a solution for this issue when I get back home.  Thanks.

**Comment by brian-j-smith** [comment]
@scidom, Mamba (0.5.0 and later) is safe to use with julia 0.4 now.  Some of Mamba's components may not be fully functional since julia 0.4 is under heavy development, but it will not hold back any of the other package (e.g. Color) versions.

**Comment by scidom** [comment]
Thanks for the update @brian-j-smith.
