### ISSUE TITLE
Documentation for custom sampler

### ISSUE THREAD

**Issue by Vgrunert** [brian-j-smith/Mamba.jl#77]
Hi,

first of all let me express my gratitude for this excellent API. Second, I am currently trying to implement and test different kind of metropolise-hastings algorithms. I read through some of the examples of the implemented samplers and came to realize that it would be great to have an pseudo example of a sampler implementation with documenation. It would make the process of implementing custom samplers much easier.

**Comment by brian-j-smith** [comment]
Hi @Vgrunert.  This is a very timely suggestion since updates to the package will be uploaded this week to simplify and better formalize the implementation of samplers.  Once the updates are up and running, I plan to start working on documentation.  I'll do what I can in between other projects that need to get finished up before Christmas, so stay tuned.
