### ISSUE TITLE
Inconsistent indexing in Chains getindex()

### ISSUE THREAD

**Issue by axsk** [brian-j-smith/Mamba.jl#87]
`sim[a:b,:,:]` refers to the original (unthinned) iterations present in sim (intersected with the thinned), which is quite reasonable.
But the step `s` in `sim[a:s:b.:,:]` actually refers to the steps in the already thinned result, i.e.
``` julia
sim[0:10:end],:,:][0:10:end,:,:] == sim[0:100:end,:,:]
```
This is quite counterintuitive to me and makes reasoning about selecting only every n-th sample cumbersome.

I think the step should, like start and stop, always refer to the original (unthinned) sampling and not the current subset/selection.

If desired I could try fixing this.

**Comment by brian-j-smith** [comment]
Currently, ``getindex`` performs "relative" thinning - thinning relative to the current chain (consistent with the documented behavior).

What you are proposing is "absolute" thinning - thinning applied to the original iterations.  Absolute thinning generally requires that all original iterations be available.  That is not necessarily the case in this setting, where thinning of thinned chains may be desired.  In particular, if absolute thinning were implemented, ``a:thin:b`` would only work when ``thin`` is a multiple of the thinning present in the current chain.  Moreover, the simple notation ``a:b``, which is equivalent to ``a:1:b``, would only work if the current chain was unthinned.  Otherwise, except for those special cases, errors would be generated.

Relative thinning is implemented partly because ``a:thin:b`` and ``a:b`` always work.

**Comment by axsk** [comment]
I see, so this is a feature :)
Guess I can live with that.
